### PR TITLE
Change ostrstream to ostringstream

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Update needed for nlp++ plugin

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@richardkchapman please merge. This is an update needed for the nlp plugin to plug a memory leak.

**Comment by dehilsterlexis** [comment]
@richardkchapman ping

**Comment by richardkchapman** [comment]
Unless there's a reason this can't or won't be submitted to the upstream repo, we should not be making changes to our fork of it

**Comment by dehilsterlexis** [comment]
I'm unfamiliar with the process of how to resolve this. The current fork needs to be updated to the latest version of the nlp-engine for the nlp plugin to work. Gordon asked me to do this but perhaps I did this incorrectly?

**Comment by richardkchapman** [comment]
I have pulled all changes over from the upstream repo to our copy, and that seems to have automatically marked this as merged, so I assume this branch was also merged upstream

**Comment by dehilsterlexis** [comment]
I will push my latest nlp plugin that calls the new nlp-engine and see if things go right.

**Pull request merged**
